let i = 0;
module.exports = {
  ERROR: {
    USER: {
      NOT_FOUND: 'ERROR.USER.NOT_FOUND',
      DUPLICATE: 'ERROR.USER.DUPLICATE'
    },
    APPLICATION: {
      NOT_FOUND: 'ERROR.APPLICATION.NOT_FOUND',
      ALREADY_SUBMITTED: 'ERROR.APPLICATION.ALREADY_SUBMITTED',
      INCOMPLETE_PARAMS: 'ERROR.APPLICATION.INCOMPLETE_PARAMS',
      ALREADY_HANDLED: 'ERROR.APPLICATION.ALREADY_HANDLED'
    },
    AUTH: {
      UNAUTHORIZED: 'ERROR.AUTH.UNAUTHORIZED',
      WRONG_CREDENTIALS: 'ERROR.AUTH.WRONG_CREDENTIALS'
    },
    DB: {
      ERROR: 'ERROR.DB.ERROR'
    },
    TOKEN: {
      VERIFY: 'ERROR.TOKEN.VERIFY',
      INVALID: 'ERROR.TOKEN.INVALID',
      NOT_SUPPLIED: 'ERROR.TOKEN.NOT_SUPPLIED'
    },
    GENERAL: {
      GENERIC: 'ERROR.GENERAL.GENERIC'
    }
  },
  SUCCESS: {
    APPLICATION: {
      SUBMITTED: 'SUCCESS.APPLICATION.SUBMITTED',
      EDITED: 'SUCCESS.APPLICATION.EDITED',
      HANDLED: 'SUCCESS.APPLICATION.HANDLED',
      DELETED: 'SUCCESS.APPLICATION.DELETED'
    },
    USER: {
      REGISTERED: 'SUCCESS.USER.REGISTERED'
    },
    AUTH: {
      SUCCESS: 'SUCCESS.AUTH.SUCCESS'
    }
  }
}